import Foundation
import SwiftData

/// A recipe the user can cook. Recipes come from three places — the bundled starter
/// library, the AI layer, and anything the user saves — and `origin` records which.
@Model
final class Recipe {
    var id: UUID = UUID()

    var title: String = ""
    var summary: String = ""
    var prepTimeMinutes: Int = 0
    var cookTimeMinutes: Int = 0
    var servings: Int = 2
    var difficultyRaw: String = RecipeDifficulty.easy.rawValue
    var cuisine: String?

    /// Free-form tags used for the Recipes tab sections and filtering,
    /// e.g. "quick", "highProtein", "vegetarian".
    var tags: [String] = []
    var equipment: [String] = []
    var steps: [String] = []

    var originRaw: String = RecipeOrigin.library.rawValue
    var isSaved: Bool = false
    var dateCreated: Date = Date.now
    var lastCookedDate: Date?
    var timesCooked: Int = 0

    /// Per serving. Marked as an estimate unless it came from verified product data.
    var nutritionData: Data?

    @Relationship(deleteRule: .cascade, inverse: \RecipeIngredient.recipe)
    var ingredients: [RecipeIngredient] = []

    @Relationship(deleteRule: .cascade, inverse: \CookingSession.recipe)
    var cookingSessions: [CookingSession] = []

    init(
        title: String,
        summary: String = "",
        prepTimeMinutes: Int = 0,
        cookTimeMinutes: Int = 0,
        servings: Int = 2,
        difficulty: RecipeDifficulty = .easy,
        cuisine: String? = nil,
        tags: [String] = [],
        equipment: [String] = [],
        steps: [String] = [],
        origin: RecipeOrigin = .library,
        isSaved: Bool = false,
        nutrition: NutritionFacts? = nil
    ) {
        self.id = UUID()
        self.title = title
        self.summary = summary
        self.prepTimeMinutes = prepTimeMinutes
        self.cookTimeMinutes = cookTimeMinutes
        self.servings = servings
        self.difficultyRaw = difficulty.rawValue
        self.cuisine = cuisine
        self.tags = tags
        self.equipment = equipment
        self.steps = steps
        self.originRaw = origin.rawValue
        self.isSaved = isSaved
        self.dateCreated = .now
        self.nutritionData = nutrition.flatMap { try? JSONEncoder().encode($0) }
    }

    // MARK: - Typed accessors

    var difficulty: RecipeDifficulty {
        get { RecipeDifficulty(rawValue: difficultyRaw) ?? .easy }
        set { difficultyRaw = newValue.rawValue }
    }

    var origin: RecipeOrigin {
        get { RecipeOrigin(rawValue: originRaw) ?? .library }
        set { originRaw = newValue.rawValue }
    }

    var nutrition: NutritionFacts? {
        get {
            guard let nutritionData else { return nil }
            return try? JSONDecoder().decode(NutritionFacts.self, from: nutritionData)
        }
        set { nutritionData = newValue.flatMap { try? JSONEncoder().encode($0) } }
    }

    var totalTimeMinutes: Int { prepTimeMinutes + cookTimeMinutes }

    var wasCooked: Bool { timesCooked > 0 }

    /// Plain-text form used by `ShareLink`.
    var shareText: String {
        var lines: [String] = [title]
        if !summary.isEmpty { lines.append(summary) }
        lines.append("")
        lines.append(String(localized: "\(totalTimeMinutes) min · \(servings) servings"))
        lines.append("")
        lines.append(String(localized: "Ingredients"))
        for ingredient in ingredients {
            lines.append("• " + ingredient.displayDescription)
        }
        lines.append("")
        lines.append(String(localized: "Method"))
        for (index, step) in steps.enumerated() {
            lines.append("\(index + 1). \(step)")
        }
        return lines.joined(separator: "\n")
    }
}

enum RecipeDifficulty: String, CaseIterable, Identifiable, Codable, Sendable {
    case easy
    case medium
    case involved

    var id: String { rawValue }

    var name: String {
        switch self {
        case .easy: return String(localized: "Easy")
        case .medium: return String(localized: "Medium")
        case .involved: return String(localized: "Involved")
        }
    }
}

enum RecipeOrigin: String, Codable, Sendable {
    /// Ships with the app and works with no network.
    case library
    /// Generated by the AI layer.
    case generated
    /// Entered by the user.
    case userCreated

    var name: String {
        switch self {
        case .library: return String(localized: "Pantry library")
        case .generated: return String(localized: "Generated")
        case .userCreated: return String(localized: "Yours")
        }
    }
}

/// Well-known tags. Recipes may carry others; these are the ones the UI groups by.
enum RecipeTag: String, CaseIterable, Identifiable, Sendable {
    case quick
    case highProtein
    case vegetarian
    case vegan
    case onePan
    case comfort
    case light

    var id: String { rawValue }

    var name: String {
        switch self {
        case .quick: return String(localized: "Quick")
        case .highProtein: return String(localized: "High Protein")
        case .vegetarian: return String(localized: "Vegetarian")
        case .vegan: return String(localized: "Vegan")
        case .onePan: return String(localized: "One Pan")
        case .comfort: return String(localized: "Comfort")
        case .light: return String(localized: "Light")
        }
    }

    var symbolName: String {
        switch self {
        case .quick: return "bolt"
        case .highProtein: return "figure.strengthtraining.traditional"
        case .vegetarian: return "leaf"
        case .vegan: return "carrot"
        case .onePan: return "frying.pan"
        case .comfort: return "heart"
        case .light: return "wind"
        }
    }
}

extension Sequence where Element == Recipe {
    /// The recipes that belong in the library.
    ///
    /// Generated suggestions the user hasn't saved are excluded: they are materialised
    /// so cooking mode, servings, sharing and shopping work on them without a parallel
    /// implementation, but until they are saved they belong only to the suggestion that
    /// produced them — surfacing them on Home or in the library would look like
    /// recipes appearing from nowhere.
    var browsable: [Recipe] {
        filter { $0.origin != .generated || $0.isSaved }
    }

    /// Generated suggestions the user never saved and hasn't looked at for a while.
    func staleSuggestions(olderThan days: Int = 7, now: Date = .now) -> [Recipe] {
        let cutoff = Calendar.current.date(byAdding: .day, value: -days, to: now) ?? now
        return filter { $0.origin == .generated && !$0.isSaved && $0.dateCreated < cutoff }
    }
}
