import SwiftUI

/// What the AI layer is doing, in a form a view can switch on. Keeping this in one type
/// means every AI-backed screen presents loading, empty, error and offline the same way.
enum AIState<Value> {
    case idle
    case loading
    case loaded(AIResult<Value>)
    case failed(AIError)

    var isLoading: Bool {
        if case .loading = self { return true }
        return false
    }

    var value: Value? {
        if case .loaded(let result) = self { return result.value }
        return nil
    }

    var result: AIResult<Value>? {
        if case .loaded(let result) = self { return result }
        return nil
    }
}

/// The line shown under generated content.
///
/// Two things are always disclosed: that a model produced this, and whether it stayed
/// on the device. If the sample provider produced it, that is said plainly — no
/// generated placeholder is ever allowed to pass as a real answer.
struct AIProvenanceFooter: View {
    var providerName: String
    var wasOnDevice: Bool
    var isSample: Bool

    var body: some View {
        Label {
            Text(text)
        } icon: {
            Image(systemName: isSample ? "hammer" : (wasOnDevice ? "iphone" : "sparkles"))
        }
        .font(.footnote)
        .foregroundStyle(.secondary)
        .accessibilityLabel(text)
    }

    private var text: String {
        if isSample {
            return String(localized: "Sample content for development — not a real suggestion.")
        }
        if wasOnDevice {
            return String(localized: "Generated on your device by \(providerName). Nothing left your iPhone.")
        }
        return String(localized: "Generated by \(providerName). Check quantities and cooking times.")
    }
}

/// The error state for anything AI-backed.
///
/// It says what happened, what still works, and offers the one action worth offering.
/// The pantry itself is never blocked by this — that is the whole point of the message.
struct AIErrorView: View {
    var error: AIError
    var retry: (() -> Void)?

    var body: some View {
        ContentUnavailableView {
            Label(error.errorDescription ?? String(localized: "Something went wrong"), systemImage: symbolName)
        } description: {
            if let suggestion = error.recoverySuggestion {
                Text(suggestion)
            }
        } actions: {
            if let retry, error.isTransient {
                Button(String(localized: "Try Again"), action: retry)
                    .buttonStyle(.bordered)
            }
        }
    }

    private var symbolName: String {
        switch error {
        case .offline: return "wifi.slash"
        case .timedOut: return "clock.badge.exclamationmark"
        case .noProviderAvailable, .notConfigured: return "sparkles"
        case .rateLimited: return "hourglass"
        default: return "exclamationmark.triangle"
        }
    }
}

/// Loading state for generated content.
///
/// A short line saying what is being worked out beats a bare spinner: the user knows
/// which request they are waiting for, and can cancel it.
struct AIProgressView: View {
    var message: String
    var cancel: (() -> Void)?

    var body: some View {
        VStack(spacing: 12) {
            ProgressView()
                .controlSize(.large)
            Text(message)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
            if let cancel {
                Button(String(localized: "Cancel"), action: cancel)
                    .buttonStyle(.borderless)
                    .font(.subheadline)
            }
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 32)
        .accessibilityElement(children: .combine)
        .accessibilityLabel(message)
    }
}

/// Shown at the top of AI-backed screens when the device has no connection and no
/// on-device model, so the user understands why a button is unavailable.
struct OfflineNoticeView: View {
    var body: some View {
        Label(
            String(localized: "You're offline. Your pantry, saved recipes and shopping list all still work."),
            systemImage: "wifi.slash"
        )
        .font(.footnote)
        .foregroundStyle(.secondary)
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

#Preview("AI states") {
    List {
        Section {
            AIProgressView(message: "Looking at what you have…", cancel: {})
        }
        Section {
            AIErrorView(error: .offline, retry: {})
        }
        Section {
            AIProvenanceFooter(providerName: "On-device", wasOnDevice: true, isSample: false)
            AIProvenanceFooter(providerName: "Groq", wasOnDevice: false, isSample: false)
            AIProvenanceFooter(providerName: "Sample responses", wasOnDevice: true, isSample: true)
        }
    }
}
