import SwiftUI
import SwiftData

/// Choosing which nutrients Pantry shows.
///
/// Nutrition is not what this app is for, so this screen's job is to let someone bring
/// forward the one or two figures they actually care about and put the rest away —
/// including all of them, which switches nutrition panels off entirely.
struct NutritionSettingsView: View {

    @Environment(\.modelContext) private var modelContext
    @Environment(AppEnvironment.self) private var appEnvironment

    @State private var preferences: UserPreferences?

    var body: some View {
        Form {
            if let preferences {
                content(for: preferences)
            }
        }
        .navigationTitle(Text("Nutrition"))
        .onAppear {
            if preferences == nil {
                preferences = PantryModelContainer.preferences(in: modelContext)
            }
        }
    }

    @ViewBuilder
    private func content(for preferences: UserPreferences) -> some View {
        Section {
            ForEach(Nutrient.allCases) { nutrient in
                Toggle(isOn: binding(for: nutrient, in: preferences)) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text(nutrient.name)
                        if let footnote = nutrient.footnote {
                            Text(footnote)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                }
            }
        } header: {
            Text("Show in Nutrition Panels")
        } footer: {
            Text("Applies to recipes and to items in your pantry. A nutrient only appears where the recipe or product actually provides a figure.")
        }

        Section {
            Button(String(localized: "Use the Standard Set")) {
                preferences.selectedNutrients = Nutrient.defaultSelection
                save(preferences)
            }
            .disabled(preferences.selectedNutrients == Nutrient.defaultSelection)

            Button(String(localized: "Turn Nutrition Off"), role: .destructive) {
                preferences.selectedNutrients = []
                save(preferences)
            }
            .disabled(preferences.selectedNutrients.isEmpty)
        } footer: {
            if preferences.selectedNutrients.isEmpty {
                Label(
                    String(localized: "Nutrition panels are hidden. Nothing else about the app changes."),
                    systemImage: "eye.slash"
                )
            }
        }

        Section {
            Text("Figures generated by the AI layer are estimates and are labelled as such wherever they appear. Nothing here is nutritional advice, and Pantry does not track what you eat.")
                .font(.footnote)
                .foregroundStyle(.secondary)
        } header: {
            Text("Where the Numbers Come From")
        }
    }

    private func binding(for nutrient: Nutrient, in preferences: UserPreferences) -> Binding<Bool> {
        Binding(
            get: { preferences.trackedNutrients.contains(nutrient.rawValue) },
            set: { isOn in
                var selection = preferences.selectedNutrients
                if isOn {
                    if !selection.contains(nutrient) { selection.append(nutrient) }
                } else {
                    selection.removeAll { $0 == nutrient }
                }
                preferences.selectedNutrients = selection
                save(preferences)
            }
        )
    }

    private func save(_ preferences: UserPreferences) {
        preferences.lastUpdated = .now
        try? modelContext.save()
        appEnvironment.preferences = PreferenceSnapshot(preferences)
    }
}

#Preview {
    NavigationStack {
        NutritionSettingsView()
    }
    .environment(AppEnvironment())
    .modelContainer(SampleData.previewContainer())
}
